/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuthenticationController } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('AuthenticationController', () => {
  let controller : AuthenticationController;

  beforeAll(() => {
    controller = new AuthenticationController(testClient);
  });

  it('should custom Authentication Test', async () => {
    const response = await makeApiCall(
      () => controller.customAuthentication()
    );

    expect(response.statusCode).toBe(200);

    const expected = 'You\'ve passed the test!';

    expect(response.result).not.toBeNull();
    expect(response.result).toEqual(expected);
  });

  it('should OAuth2Test', async () => {
    const response = await makeApiCall(() => controller.oAuthBearerToken());

    expect(response.statusCode).toBe(200);

    const expected = 'You\'ve passed the test!';

    expect(response.result).not.toBeNull();
    expect(response.result).toEqual(expected);
  });

  it('should check service status', async () => {
    const response = await makeApiCall(
      () => controller.oAuthClientCredentialsGrant()
    );

    expect(response.statusCode).toBe(200);
  });

  it('should custom query param test', async () => {
    const response = await makeApiCall(
      () => controller.customQueryOrHeaderAuthentication()
    );

    expect(response.statusCode).toBe(200);

    const expected = 'You\'ve passed the test!';

    expect(response.result).not.toBeNull();
    expect(response.result).toEqual(expected);
  });

  it('should BasicAuthAndApiKeyAndApiHeader', async () => {
    const response = await makeApiCall(
      () => controller.basicAuthAndApiHeaderAuth()
    );

    expect(response.statusCode).toBe(200);

    const expected = 'You\'ve passed the test!';

    expect(response.result).not.toBeNull();
    expect(response.result).toEqual(expected);
  });

  it('should OAuthOrCombinationTest', async () => {
    const response = await makeApiCall(
      () => controller.oAuthGrantTypesORCombinations()
    );

    expect(response.statusCode).toBe(200);

    const expected = 'You\'ve passed the test!';

    expect(response.result).not.toBeNull();
    expect(response.result).toEqual(expected);
  });

  it('should MultipleAuthOrCombinationTest', async () => {
    const response = await makeApiCall(
      () => controller.multipleAuthCombination()
    );

    expect(response.statusCode).toBe(200);

    const expected = 'You\'ve passed the test!';

    expect(response.result).not.toBeNull();
    expect(response.result).toEqual(expected);
  });
});
