/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment, SuiteCodeEnum } from '../src';

const defaultTestConfiguration: Partial<Configuration> = {
  accessToken2: 'azHmdOe09EdchxeWsdnplkQbv76sJH',
  basicAuthCredentials: { username: 'Zeeshan', password: 'bhai_99' },
  apiKeyCredentials: {
    token: 'asdqwaxr2gSdhasWSDbdAgdA637sdAhde7Adysi23',
    'api-key': 'api-key',
  },
  apiHeaderCredentials: {
    token: 'Qaws2W233WedeRe4T56G6Vref2',
    'api-key': 'api-key',
  },
  oAuthCCGCredentials: {
    oAuthClientId: '23',
    oAuthClientSecret: 'tQNSqQlXBIwZcY9auoujQ57ckDcoh3t8UPbBRkSF',
  },
  oAuthACGCredentials: {
    oAuthClientId: '24',
    oAuthClientSecret: 'Y9auoujQ57ckDtQNSqQlXBIwZccoh3t8UPbBRkSF',
    oAuthRedirectUri: 'x',
    oAuthTokenProvider: (_, authManager) =>
      authManager.fetchToken('910b000d4f'),
  },
  oAuthROPCGCredentials: {
    oAuthClientId: '25',
    oAuthClientSecret: 'ckDcoh3t8UPbBRkSFtQNSqQlXBIwZcY9auoujQ57',
    oAuthUsername: 'apimatic',
    oAuthPassword: 'api-d604257e42-matic',
  },
  oAuthBearerTokenCredentials: {
    accessToken: '0b79bab50daca910b000d4f1a2b675d604257e42',
  },
};

export const testClient = new Client({
  ...createConfigurationFromEnvironment(),
  ...defaultTestConfiguration,
});

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.MULTI_AUTH_SAMPLE_LIB_ENVIRONMENT;
  const port = process.env.MULTI_AUTH_SAMPLE_LIB_PORT;
  const suites = process.env.MULTI_AUTH_SAMPLE_LIB_SUITES;
  const timeout = process.env.MULTI_AUTH_SAMPLE_LIB_TIMEOUT;
  const accessToken2 = process.env.MULTI_AUTH_SAMPLE_LIB_ACCESS_TOKEN_2;
  const username = process.env.MULTI_AUTH_SAMPLE_LIB_USERNAME;
  const password = process.env.MULTI_AUTH_SAMPLE_LIB_PASSWORD;
  const token = process.env.MULTI_AUTH_SAMPLE_LIB_TOKEN;
  const apiKey = process.env.MULTI_AUTH_SAMPLE_LIB_API_KEY;
  const token2 = process.env.MULTI_AUTH_SAMPLE_LIB_TOKEN_2;
  const apiKey2 = process.env.MULTI_AUTH_SAMPLE_LIB_API_KEY_2;
  const oAuthClientId = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_ID;
  const oAuthClientSecret = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_SECRET;
  const oAuthClientId2 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_ID_2;
  const oAuthClientSecret2 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_SECRET_2;
  const oAuthRedirectUri2 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_REDIRECT_URI_2;
  const oAuthClientId3 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_ID_3;
  const oAuthClientSecret3 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_SECRET_3;
  const oAuthUsername3 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_USERNAME_3;
  const oAuthPassword3 = process.env.MULTI_AUTH_SAMPLE_LIB_O_AUTH_PASSWORD_3;
  const accessToken = process.env.MULTI_AUTH_SAMPLE_LIB_ACCESS_TOKEN;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (port !== undefined) {
    config.port = port;
  }

  if (suites !== undefined && suites !== '') {
    config.suites = parseInt(suites) as SuiteCodeEnum;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (accessToken2 !== undefined) {
    config.accessToken2 = accessToken2;
  }

  if (username !== undefined && password !== undefined) {
    config.basicAuthCredentials = { username: username, password: password };
  }

  if (token !== undefined && apiKey !== undefined) {
    config.apiKeyCredentials = { token: token, 'api-key': apiKey };
  }

  if (token2 !== undefined && apiKey2 !== undefined) {
    config.apiHeaderCredentials = { token: token2, 'api-key': apiKey2 };
  }

  if (oAuthClientId !== undefined && oAuthClientSecret !== undefined) {
    config.oAuthCCGCredentials = {
      oAuthClientId: oAuthClientId,
      oAuthClientSecret: oAuthClientSecret,
    };
  }

  if (
    oAuthClientId2 !== undefined
    && oAuthClientSecret2 !== undefined
    && oAuthRedirectUri2 !== undefined
  ) {
    config.oAuthACGCredentials = {
      oAuthClientId: oAuthClientId2,
      oAuthClientSecret: oAuthClientSecret2,
      oAuthRedirectUri: oAuthRedirectUri2,
    };
  }

  if (
    oAuthClientId3 !== undefined
    && oAuthClientSecret3 !== undefined
    && oAuthUsername3 !== undefined
    && oAuthPassword3 !== undefined
  ) {
    config.oAuthROPCGCredentials = {
      oAuthClientId: oAuthClientId3,
      oAuthClientSecret: oAuthClientSecret3,
      oAuthUsername: oAuthUsername3,
      oAuthPassword: oAuthPassword3,
    };
  }

  if (accessToken !== undefined) {
    config.oAuthBearerTokenCredentials = { accessToken: accessToken };
  }

  return config;
}
