/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { OAuthToken, oAuthTokenSchema } from '../models/oAuthToken.js';
import { optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { OAuthProviderError } from '../errors/oAuthProviderError.js';

export class OAuthAuthorizationController extends BaseController {
  /**
   * Create a new OAuth 2 token.
   *
   * @param authorization Authorization header in Basic auth format
   * @param scope         Requested scopes as a space-delimited list.
   * @return Response from the API call
   */
  async requestTokenOAuthCCG(
    authorization: string,
    scope?: string,
    fieldParameters?: Record<string, unknown>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OAuthToken>> {
    const req = this.createRequest('POST', '/request_token');
    req.baseUrl('auth');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      scope: [scope, optional(string())],
    });
    req.header('Authorization', mapped.authorization);
    req.form({
      grant_type: 'client_credentials',
      scope: mapped.scope,
      ...fieldParameters,
    });
    req.throwOn(400, OAuthProviderError, 'OAuth 2 provider returned an error.');
    req.throwOn(
      401,
      OAuthProviderError,
      'OAuth 2 provider says client authentication failed.'
    );
    req.authenticate(false);
    return req.callAsJson(oAuthTokenSchema, requestOptions);
  }

  /**
   * Create a new OAuth 2 token.
   *
   * @param authorization Authorization header in Basic auth format
   * @param code          Authorization Code
   * @param redirectUri   Redirect Uri
   * @return Response from the API call
   */
  async requestTokenOAuthACG(
    authorization: string,
    code: string,
    redirectUri: string,
    fieldParameters?: Record<string, unknown>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OAuthToken>> {
    const req = this.createRequest('POST', '/oauth2/non-auth-server/token');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      code: [code, string()],
      redirectUri: [redirectUri, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.form({
      grant_type: 'authorization_code',
      code: mapped.code,
      redirect_uri: mapped.redirectUri,
      ...fieldParameters,
    });
    req.throwOn(400, OAuthProviderError, 'OAuth 2 provider returned an error.');
    req.throwOn(
      401,
      OAuthProviderError,
      'OAuth 2 provider says client authentication failed.'
    );
    req.authenticate(false);
    return req.callAsJson(oAuthTokenSchema, requestOptions);
  }

  /**
   * Obtain a new access token using a refresh token
   *
   * @param authorization Authorization header in Basic auth format
   * @param refreshToken  Refresh token
   * @param scope         Requested scopes as a space-delimited list.
   * @return Response from the API call
   */
  async refreshTokenOAuthACG(
    authorization: string,
    refreshToken: string,
    scope?: string,
    fieldParameters?: Record<string, unknown>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OAuthToken>> {
    const req = this.createRequest('POST', '/oauth2/non-auth-server/token');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      refreshToken: [refreshToken, string()],
      scope: [scope, optional(string())],
    });
    req.header('Authorization', mapped.authorization);
    req.form({
      grant_type: 'refresh_token',
      refresh_token: mapped.refreshToken,
      scope: mapped.scope,
      ...fieldParameters,
    });
    req.throwOn(400, OAuthProviderError, 'OAuth 2 provider returned an error.');
    req.throwOn(
      401,
      OAuthProviderError,
      'OAuth 2 provider says client authentication failed.'
    );
    req.authenticate(false);
    return req.callAsJson(oAuthTokenSchema, requestOptions);
  }

  /**
   * Create a new OAuth 2 token.
   *
   * @param authorization Authorization header in Basic auth format
   * @param username      Resource owner username
   * @param password      Resource owner password
   * @param scope         Requested scopes as a space-delimited list.
   * @return Response from the API call
   */
  async requestTokenOAuthROPCG(
    authorization: string,
    username: string,
    password: string,
    scope?: string,
    fieldParameters?: Record<string, unknown>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OAuthToken>> {
    const req = this.createRequest('POST', '/oauth2/non-auth-server/token');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      username: [username, string()],
      password: [password, string()],
      scope: [scope, optional(string())],
    });
    req.header('Authorization', mapped.authorization);
    req.form({
      grant_type: 'password',
      username: mapped.username,
      password: mapped.password,
      scope: mapped.scope,
      ...fieldParameters,
    });
    req.throwOn(400, OAuthProviderError, 'OAuth 2 provider returned an error.');
    req.throwOn(
      401,
      OAuthProviderError,
      'OAuth 2 provider says client authentication failed.'
    );
    req.authenticate(false);
    return req.callAsJson(oAuthTokenSchema, requestOptions);
  }

  /**
   * Obtain a new access token using a refresh token
   *
   * @param authorization Authorization header in Basic auth format
   * @param refreshToken  Refresh token
   * @param scope         Requested scopes as a space-delimited list.
   * @return Response from the API call
   */
  async refreshTokenOAuthROPCG(
    authorization: string,
    refreshToken: string,
    scope?: string,
    fieldParameters?: Record<string, unknown>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OAuthToken>> {
    const req = this.createRequest('POST', '/oauth2/non-auth-server/token');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      refreshToken: [refreshToken, string()],
      scope: [scope, optional(string())],
    });
    req.header('Authorization', mapped.authorization);
    req.form({
      grant_type: 'refresh_token',
      refresh_token: mapped.refreshToken,
      scope: mapped.scope,
      ...fieldParameters,
    });
    req.throwOn(400, OAuthProviderError, 'OAuth 2 provider returned an error.');
    req.throwOn(
      401,
      OAuthProviderError,
      'OAuth 2 provider says client authentication failed.'
    );
    req.authenticate(false);
    return req.callAsJson(oAuthTokenSchema, requestOptions);
  }
}
