/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScopeOAuthACGEnum
 */
export enum OAuthScopeOAuthACGEnum {
  ReadScope = 'file_requests.read',
}

/**
 * Schema for OAuthScopeOAuthACGEnum
 */
export const oAuthScopeOAuthACGEnumSchema: Schema<OAuthScopeOAuthACGEnum> = stringEnum(
  OAuthScopeOAuthACGEnum
);
