/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  basicAuthenticationProvider,
  compositeAuthenticationProvider,
  customAuthenticationProvider,
  customHeaderAuthenticationProvider,
  customQueryAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';
import { OAuthToken } from './models/oAuthToken.js';
import { OAuthACGManager } from './oAuthACGManager.js';
import { OAuthCCGManager } from './oAuthCCGManager.js';
import { OAuthROPCGManager } from './oAuthROPCGManager.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  oAuthCCG: () => OAuthCCGManager | undefined,
  oAuthACG: () => OAuthACGManager | undefined,
  oAuthROPCG: () => OAuthROPCGManager | undefined
) {
  const authConfig = {
    basicAuth:
      config.basicAuthCredentials &&
      basicAuthenticationProvider(
        config.basicAuthCredentials.username,
        config.basicAuthCredentials.password
      ),
    apiKey:
      config.apiKeyCredentials &&
      customQueryAuthenticationProvider(config.apiKeyCredentials),
    apiHeader:
      config.apiHeaderCredentials &&
      customHeaderAuthenticationProvider(config.apiHeaderCredentials),
    oAuthCCG:
      config.oAuthCCGCredentials &&
      requestAuthenticationProvider(
        config.oAuthCCGCredentials.oAuthToken,
        oAuthCCGTokenProvider(
          oAuthCCG,
          config.oAuthCCGCredentials.oAuthTokenProvider
        ),
        config.oAuthCCGCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.oAuthCCGCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
    oAuthACG:
      config.oAuthACGCredentials &&
      requestAuthenticationProvider(
        config.oAuthACGCredentials.oAuthToken,
        oAuthACGTokenProvider(
          oAuthACG,
          config.oAuthACGCredentials.oAuthTokenProvider
        ),
        config.oAuthACGCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.oAuthACGCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
    oAuthROPCG:
      config.oAuthROPCGCredentials &&
      requestAuthenticationProvider(
        config.oAuthROPCGCredentials.oAuthToken,
        oAuthROPCGTokenProvider(
          oAuthROPCG,
          config.oAuthROPCGCredentials.oAuthTokenProvider
        ),
        config.oAuthROPCGCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.oAuthROPCGCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
    oAuthBearerToken:
      config.oAuthBearerTokenCredentials &&
      accessTokenAuthenticationProvider(config.oAuthBearerTokenCredentials),
    customAuth:
      config.customAuthCredentials &&
      customAuthenticationProvider(config.customAuthCredentials),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function oAuthCCGTokenProvider(
  oAuthCCG: () => OAuthCCGManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: OAuthCCGManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oAuthCCG();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}

function oAuthACGTokenProvider(
  oAuthACG: () => OAuthACGManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: OAuthACGManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oAuthACG();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}

function oAuthROPCGTokenProvider(
  oAuthROPCG: () => OAuthROPCGManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: OAuthROPCGManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oAuthROPCG();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
