/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter.js';
import {
  OAuthScopeOAuthACGEnum,
  oAuthScopeOAuthACGEnumSchema,
} from './models/oAuthScopeOAuthACGEnum.js';
import { OAuthToken } from './models/oAuthToken.js';
import { SuiteCodeEnum, suiteCodeEnumSchema } from './models/suiteCodeEnum.js';
import { OAuthACGManager } from './oAuthACGManager.js';
import { OAuthCCGManager } from './oAuthCCGManager.js';
import { OAuthROPCGManager } from './oAuthROPCGManager.js';
import {
  anyOf,
  array,
  boolean,
  literal,
  number,
  object,
  optional,
  Schema,
  string,
  stringEnum,
  validateAndMap,
} from './schema.js';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  accessToken2: string;
  environment: Environment;
  port: string;
  suites: SuiteCodeEnum;
  basicAuthCredentials?: {
    username: string;
    password: string;
  };
  apiKeyCredentials?: {
    'token': string;
    'api-key': string;
  };
  apiHeaderCredentials?: {
    'token': string;
    'api-key': string;
  };
  oAuthCCGCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthToken?: OAuthToken;
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: OAuthCCGManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  oAuthACGCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthRedirectUri: string;
    oAuthToken?: OAuthToken;
    oAuthScopes?: OAuthScopeOAuthACGEnum[];
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: OAuthACGManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  oAuthROPCGCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthUsername: string;
    oAuthPassword: string;
    oAuthToken?: OAuthToken;
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: OAuthROPCGManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  oAuthBearerTokenCredentials?: {
    accessToken: string;
  };
  customAuthCredentials?: any;
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
  Testing = 'testing',
}

export namespace Configuration {
  export function fromJsonConfig(jsonConfig: string): Partial<Configuration> {
    const configurationObject = JSON.parse(jsonConfig);
    const result = validateAndMap(jsonConfig, configurationObject);

    if (result.errors) {
      throw new Error(
        'Invalid configuration provided. Please check the following errors:\n' +
          result.errors.map((e: any) => e.message).join('\n')
      );
    }

    return result.result;
  }

  export function fromEnvironment(
    envVariables: Record<string, string | undefined>
  ): Partial<Configuration> {
    const config: any = {};

    config.timeout = envVariables.TIMEOUT;
    config.environment = envVariables.ENVIRONMENT;
    config.port = envVariables.PORT;
    config.suites = envVariables.SUITES;
    config.accessToken = envVariables.ACCESS_TOKEN;

    if (envVariables.BASIC_AUTH_USERNAME && envVariables.BASIC_AUTH_PASSWORD) {
      config.basicAuthCredentials = {
        username: envVariables.BASIC_AUTH_USERNAME,
        password: envVariables.BASIC_AUTH_PASSWORD,
      };
    }

    if (envVariables.API_KEY_TOKEN && envVariables.API_KEY_API_KEY) {
      config.apiKeyCredentials = {
        token: envVariables.API_KEY_TOKEN,
        'api-key': envVariables.API_KEY_API_KEY,
      };
    }

    if (envVariables.API_HEADER_TOKEN && envVariables.API_HEADER_API_KEY) {
      config.apiHeaderCredentials = {
        token: envVariables.API_HEADER_TOKEN,
        'api-key': envVariables.API_HEADER_API_KEY,
      };
    }

    if (
      envVariables.O_AUTH_CCG_O_AUTH_CLIENT_ID &&
      envVariables.O_AUTH_CCG_O_AUTH_CLIENT_SECRET
    ) {
      config.oAuthCCGCredentials = {
        oAuthClientId: envVariables.O_AUTH_CCG_O_AUTH_CLIENT_ID,
        oAuthClientSecret: envVariables.O_AUTH_CCG_O_AUTH_CLIENT_SECRET,
        oAuthToken: envVariables.O_AUTH_CCG_O_AUTH_TOKEN,
        oAuthClockSkew: envVariables.O_AUTH_CCG_O_AUTH_CLOCK_SKEW,
      };
    }

    if (
      envVariables.O_AUTH_ACG_O_AUTH_CLIENT_ID &&
      envVariables.O_AUTH_ACG_O_AUTH_CLIENT_SECRET &&
      envVariables.O_AUTH_ACG_O_AUTH_REDIRECT_URI
    ) {
      config.oAuthACGCredentials = {
        oAuthClientId: envVariables.O_AUTH_ACG_O_AUTH_CLIENT_ID,
        oAuthClientSecret: envVariables.O_AUTH_ACG_O_AUTH_CLIENT_SECRET,
        oAuthRedirectUri: envVariables.O_AUTH_ACG_O_AUTH_REDIRECT_URI,
        oAuthToken: envVariables.O_AUTH_ACG_O_AUTH_TOKEN,
        oAuthScopes: envVariables.O_AUTH_ACG_O_AUTH_SCOPES,
        oAuthClockSkew: envVariables.O_AUTH_ACG_O_AUTH_CLOCK_SKEW,
      };
    }

    if (
      envVariables.O_AUTH_ROPCG_O_AUTH_CLIENT_ID &&
      envVariables.O_AUTH_ROPCG_O_AUTH_CLIENT_SECRET &&
      envVariables.O_AUTH_ROPCG_O_AUTH_USERNAME &&
      envVariables.O_AUTH_ROPCG_O_AUTH_PASSWORD
    ) {
      config.oAuthROPCGCredentials = {
        oAuthClientId: envVariables.O_AUTH_ROPCG_O_AUTH_CLIENT_ID,
        oAuthClientSecret: envVariables.O_AUTH_ROPCG_O_AUTH_CLIENT_SECRET,
        oAuthUsername: envVariables.O_AUTH_ROPCG_O_AUTH_USERNAME,
        oAuthPassword: envVariables.O_AUTH_ROPCG_O_AUTH_PASSWORD,
        oAuthToken: envVariables.O_AUTH_ROPCG_O_AUTH_TOKEN,
        oAuthClockSkew: envVariables.O_AUTH_ROPCG_O_AUTH_CLOCK_SKEW,
      };
    }

    if (envVariables.O_AUTH_BEARER_TOKEN_ACCESS_TOKEN) {
      config.oAuthBearerTokenCredentials = {
        accessToken: envVariables.O_AUTH_BEARER_TOKEN_ACCESS_TOKEN,
      };
    }

    config.httpClientOptions = {
      timeout: envVariables.TIMEOUT,
      retryConfig: {
        retryOnTimeout: envVariables.RETRY_ON_TIMEOUT,
        retryInterval: envVariables.RETRY_INTERVAL,
        maxNumberOfRetries: envVariables.MAX_NUMBER_OF_RETRIES,
        maximumRetryWaitTime: envVariables.MAX_RETRY_WAIT_TIME,
        backoffFactor: envVariables.RETRY_BACKOFF_FACTOR,
        httpStatusCodesToRetry: envVariables.HTTP_STATUS_CODES_TO_RETRY?.split(
          ','
        ).map((s) => s.trim()),
        httpMethodsToRetry: envVariables.HTTP_METHODS_TO_RETRY?.split(
          ','
        ).map((s) => s.trim()),
      },
    };

    if (envVariables.PROXY_ADDRESS) {
      config.httpClientOptions.proxySettings = {
        address: envVariables.PROXY_ADDRESS,
        port: envVariables.PROXY_PORT,
      };

      if (
        envVariables.PROXY_AUTH_USERNAME &&
        envVariables.PROXY_AUTH_PASSWORD
      ) {
        config.httpClientOptions.proxySettings.auth = {
          username: envVariables.PROXY_AUTH_USERNAME,
          password: envVariables.PROXY_AUTH_PASSWORD,
        };
      }
    }

    const result = validateAndMap(config, configurationSchema);

    if (result.errors) {
      throw new Error(
        'Invalid configuration provided. Please check the following errors:\n' +
          result.errors.map((e: any) => e.message).join('\n')
      );
    }

    return result.result;
  }
}

const configurationSchema: Schema<Partial<Configuration>> = object({
  timeout: ['timeout', optional(number())],
  environment: ['environment', optional(stringEnum(Environment))],
  basicAuthCredentials: [
    'basicAuthCredentials',
    optional(
      object({
        username: ['username', string()],
        password: ['password', string()],
      })
    ),
  ],
  apiKeyCredentials: [
    'apiKeyCredentials',
    optional(
      object({ token: ['token', string()], 'api-key': ['api-key', string()] })
    ),
  ],
  apiHeaderCredentials: [
    'apiHeaderCredentials',
    optional(
      object({ token: ['token', string()], 'api-key': ['api-key', string()] })
    ),
  ],
  oAuthCCGCredentials: [
    'oAuthCCGCredentials',
    optional(
      object({
        oAuthClientId: ['oAuthClientId', string()],
        oAuthClientSecret: ['oAuthClientSecret', string()],
        oAuthClockSkew: ['oAuthClockSkew', optional(number())],
      })
    ),
  ],
  oAuthACGCredentials: [
    'oAuthACGCredentials',
    optional(
      object({
        oAuthClientId: ['oAuthClientId', string()],
        oAuthClientSecret: ['oAuthClientSecret', string()],
        oAuthRedirectUri: ['oAuthRedirectUri', string()],
        oAuthScopes: [
          'oAuthScopes',
          optional(array(oAuthScopeOAuthACGEnumSchema)),
        ],
        oAuthClockSkew: ['oAuthClockSkew', optional(number())],
      })
    ),
  ],
  oAuthROPCGCredentials: [
    'oAuthROPCGCredentials',
    optional(
      object({
        oAuthClientId: ['oAuthClientId', string()],
        oAuthClientSecret: ['oAuthClientSecret', string()],
        oAuthUsername: ['oAuthUsername', string()],
        oAuthPassword: ['oAuthPassword', string()],
        oAuthClockSkew: ['oAuthClockSkew', optional(number())],
      })
    ),
  ],
  oAuthBearerTokenCredentials: [
    'oAuthBearerTokenCredentials',
    optional(object({ accessToken: ['accessToken', string()] })),
  ],
  httpClientOptions: [
    'httpClientOptions',
    optional(
      object({
        timeout: ['timeout', optional(number())],
        retryConfig: [
          'retryConfig',
          optional(
            object({
              maxNumberOfRetries: ['maxNumberOfRetries', optional(number())],
              retryOnTimeout: ['retryOnTimeout', optional(boolean())],
              retryInterval: ['retryInterval', optional(number())],
              maximumRetryWaitTime: [
                'maximumRetryWaitTime',
                optional(number()),
              ],
              backoffFactor: ['backoffFactor', optional(number())],
              httpStatusCodesToRetry: [
                'httpStatusCodesToRetry',
                optional(array(number())),
              ],
              httpMethodsToRetry: [
                'httpMethodsToRetry',
                optional(
                  array(
                    anyOf([
                      literal('GET'),
                      literal('DELETE'),
                      literal('HEAD'),
                      literal('OPTIONS'),
                      literal('POST'),
                      literal('PUT'),
                      literal('PATCH'),
                      literal('LINK'),
                      literal('UNLINK'),
                    ])
                  )
                ),
              ],
            })
          ),
        ],
        proxySettings: [
          'proxySettings',
          optional(
            object({
              address: ['address', string()],
              port: ['port', optional(number())],
              auth: [
                'auth',
                optional(
                  object({
                    username: ['username', string()],
                    password: ['password', string()],
                  })
                ),
              ],
            })
          ),
        ],
      })
    ),
  ],
  port: ['port', optional(string())],
  suites: ['suites', optional(suiteCodeEnumSchema)],
  accessToken: ['accessToken', optional(string())],
});
