/**
 * MultiAuth-SampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isExpired, isValid } from './authentication.js';
import { OAuthToken } from './models/oAuthToken.js';
import { ClientInterface } from './clientInterface.js';
import { OAuthAuthorizationController } from './controllers/oAuthAuthorizationController.js';

export class OAuthROPCGManager {
  private _oAuthClientId: string;
  private _oAuthClientSecret: string;
  private _oAuthUsername: string;
  private _oAuthPassword: string;
  private _oAuthToken?: OAuthToken;
  private _oAuthClockSkew?: number;
  private _oAuthController: OAuthAuthorizationController;

  constructor(
    {
      oAuthClientId,
      oAuthClientSecret,
      oAuthUsername,
      oAuthPassword,
      oAuthToken,
      oAuthClockSkew,
    }: {
      oAuthClientId: string;
      oAuthClientSecret: string;
      oAuthUsername: string;
      oAuthPassword: string;
      oAuthToken?: OAuthToken;
      oAuthClockSkew?: number;
    },
    client: ClientInterface
  ) {
    this._oAuthClientId = oAuthClientId;
    this._oAuthClientSecret = oAuthClientSecret;
    this._oAuthUsername = oAuthUsername;
    this._oAuthPassword = oAuthPassword;
    this._oAuthToken = oAuthToken;
    this._oAuthClockSkew = oAuthClockSkew;
    this._oAuthController = new OAuthAuthorizationController(client);
  }

  public async updateToken(oAuthToken?: OAuthToken): Promise<OAuthToken> {
    if (!this.isValid(oAuthToken)) {
      oAuthToken = await this.fetchToken();
    } else if (this.isExpired(oAuthToken)) {
      oAuthToken = await this.refreshToken();
    }
    return oAuthToken;
  }

  public isValid(oAuthToken: OAuthToken | undefined): oAuthToken is OAuthToken {
    return isValid(oAuthToken);
  }

  public isExpired(oAuthToken: OAuthToken) {
    return isExpired(oAuthToken, this._oAuthClockSkew);
  }

  public async fetchToken(
    additionalParams?: Record<string, unknown>
  ): Promise<OAuthToken> {
    const authorization = this.getClientBasicAuth(
      this._oAuthClientId,
      this._oAuthClientSecret
    );
    const { result } = await this._oAuthController.requestTokenOAuthROPCG(
      authorization,
      this._oAuthUsername,
      this._oAuthPassword,
      undefined,
      additionalParams
    );
    return this.setExpiry(result);
  }

  public async refreshToken(
    additionalParams?: Record<string, unknown>
  ): Promise<OAuthToken> {
    if (typeof this._oAuthToken?.refreshToken === 'undefined') {
      throw new Error();
    }
    const authorization = this.getClientBasicAuth(
      this._oAuthClientId,
      this._oAuthClientSecret
    );
    const { result } = await this._oAuthController.refreshTokenOAuthROPCG(
      authorization,
      this._oAuthToken?.refreshToken,
      undefined,
      additionalParams
    );
    return this.setExpiry(result);
  }

  private getClientBasicAuth(clientId: string, clientSecret: string): string {
    return `Basic ${Buffer.from(clientId + ':' + clientSecret).toString(
      'base64'
    )}`;
  }

  private async setExpiry(token: OAuthToken) {
    const newToken = token;
    if (newToken.expiresIn) {
      newToken.expiry =
        BigInt(Math.round(Date.now() / 1000)) + newToken.expiresIn;
    }
    return newToken;
  }
}
